name: Publish docker image

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
            - run: yarn ci
            - run: yarn build

    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
            - run: yarn ci
            - run: yarn test

    # Based on https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
    docker:
        needs:
            - build
            - tests
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  tags: dprslt/enphase-cyrilc-dimmer:latest
                  platforms: linux/amd64,linux/arm/v7
                  push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
